# Generated by Django 3.2.6 on 2021-08-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
